services:
  app:
    build: .
    ports:
      - "3003:3000"
    env_file:
      - .env
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: postgres_dev3
    environment:
      POSTGRES_DB: tatovacesta_dev3
      POSTGRES_PASSWORD: secure_password_dev3
      POSTGRES_USER: tatovacesta
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev3:/var/lib/postgresql/data

volumes:
  postgres_data_dev3:

