services:
  app:
    build: .
    ports:
      - "3003:3000"
    env_file:
      - .env
    environment:
      - PORT=3000
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL:-postgresql://tatovacesta:secure_password_dev3@postgres_dev3:5432/tatovacesta_dev3?schema=public}
      - JWT_SECRET=${JWT_SECRET:-dev3_super_secret_jwt_key}
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: postgres_dev3
    environment:
      POSTGRES_DB: tatovacesta_dev3
      POSTGRES_PASSWORD: secure_password_dev3
      POSTGRES_USER: tatovacesta
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev3:/var/lib/postgresql/data

volumes:
  postgres_data_dev3:

