import { ControlPlaneOperationDef, ControlPlaneOperationId } from '../types/controlPlane';

export const ControlPlaneOperationCatalog: Record<ControlPlaneOperationId, ControlPlaneOperationDef> = {
  CONTENT_READ: {
    id: 'CONTENT_READ',
    description: 'Read CMS content',
    requiredCapability: 'content.read',
    riskLevel: 'LOW',
    requiresSnapshot: false,
    requiresApproval: false,
    reversible: false,
    allowedStates: ['EXECUTING', 'COMPLETED', 'FAILED'],
    auditEvent: 'CONTENT_READ',
    forbiddenTargets: ['secrets', 'users.password'],
  },
  CONTENT_UPDATE: {
    id: 'CONTENT_UPDATE',
    description: 'Update CMS content',
    requiredCapability: 'content.write',
    riskLevel: 'MEDIUM',
    requiresSnapshot: true,
    requiresApproval: false,
    reversible: true,
    allowedStates: ['EXECUTING', 'COMPLETED', 'FAILED', 'ROLLBACK_IN_PROGRESS', 'ROLLED_BACK'],
    auditEvent: 'CONTENT_UPDATED',
    forbiddenTargets: ['secrets'],
  },
  CMS_PAGE_CREATE: {
    id: 'CMS_PAGE_CREATE',
    description: 'Create a new CMS page',
    requiredCapability: 'cms.write',
    riskLevel: 'MEDIUM',
    requiresSnapshot: true,
    requiresApproval: false,
    reversible: true,
    allowedStates: ['EXECUTING', 'COMPLETED', 'FAILED', 'ROLLBACK_IN_PROGRESS', 'ROLLED_BACK'],
    auditEvent: 'CMS_PAGE_CREATED',
    forbiddenTargets: [],
  },
  CMS_PAGE_UPDATE: {
    id: 'CMS_PAGE_UPDATE',
    description: 'Update a CMS page',
    requiredCapability: 'cms.write',
    riskLevel: 'MEDIUM',
    requiresSnapshot: true,
    requiresApproval: false,
    reversible: true,
    allowedStates: ['EXECUTING', 'COMPLETED', 'FAILED', 'ROLLBACK_IN_PROGRESS', 'ROLLED_BACK'],
    auditEvent: 'CMS_PAGE_UPDATED',
    forbiddenTargets: [],
  },
  CMS_PAGE_DELETE: {
    id: 'CMS_PAGE_DELETE',
    description: 'Delete a CMS page',
    requiredCapability: 'cms.write',
    riskLevel: 'HIGH',
    requiresSnapshot: true,
    requiresApproval: true,
    reversible: true,
    allowedStates: ['EXECUTING', 'COMPLETED', 'FAILED', 'ROLLBACK_IN_PROGRESS', 'ROLLED_BACK'],
    auditEvent: 'CMS_PAGE_DELETED',
    forbiddenTargets: [],
  },
  CONFIG_READ: {
    id: 'CONFIG_READ',
    description: 'Read system configuration',
    requiredCapability: 'settings.read',
    riskLevel: 'LOW',
    requiresSnapshot: false,
    requiresApproval: false,
    reversible: false,
    allowedStates: ['EXECUTING', 'COMPLETED', 'FAILED'],
    auditEvent: 'CONFIG_READ',
    forbiddenTargets: ['env.secrets', 'database.url'],
  },
  CONFIG_UPDATE: {
    id: 'CONFIG_UPDATE',
    description: 'Update system configuration',
    requiredCapability: 'settings.write',
    riskLevel: 'HIGH',
    requiresSnapshot: true,
    requiresApproval: true,
    reversible: true,
    allowedStates: ['EXECUTING', 'COMPLETED', 'FAILED', 'ROLLBACK_IN_PROGRESS', 'ROLLED_BACK'],
    auditEvent: 'CONFIG_UPDATED',
    forbiddenTargets: ['env.secrets', 'database.url'],
  },
  FEATURE_ENABLE: {
    id: 'FEATURE_ENABLE',
    description: 'Enable a feature flag',
    requiredCapability: 'settings.write',
    riskLevel: 'MEDIUM',
    requiresSnapshot: true,
    requiresApproval: false,
    reversible: true,
    allowedStates: ['EXECUTING', 'COMPLETED', 'FAILED', 'ROLLBACK_IN_PROGRESS', 'ROLLED_BACK'],
    auditEvent: 'FEATURE_ENABLED',
    forbiddenTargets: [],
  },
  FEATURE_DISABLE: {
    id: 'FEATURE_DISABLE',
    description: 'Disable a feature flag',
    requiredCapability: 'settings.write',
    riskLevel: 'MEDIUM',
    requiresSnapshot: true,
    requiresApproval: false,
    reversible: true,
    allowedStates: ['EXECUTING', 'COMPLETED', 'FAILED', 'ROLLBACK_IN_PROGRESS', 'ROLLED_BACK'],
    auditEvent: 'FEATURE_DISABLED',
    forbiddenTargets: [],
  },
  QA_RUN: {
    id: 'QA_RUN',
    description: 'Run QA process',
    requiredCapability: 'qa.run',
    riskLevel: 'LOW',
    requiresSnapshot: false,
    requiresApproval: false,
    reversible: false,
    allowedStates: ['EXECUTING', 'COMPLETED', 'FAILED'],
    auditEvent: 'QA_RUN',
    forbiddenTargets: [],
  },
  AUDIT_RUN: {
    id: 'AUDIT_RUN',
    description: 'Run Audit',
    requiredCapability: 'audit.run',
    riskLevel: 'LOW',
    requiresSnapshot: false,
    requiresApproval: false,
    reversible: false,
    allowedStates: ['EXECUTING', 'COMPLETED', 'FAILED'],
    auditEvent: 'AUDIT_RUN',
    forbiddenTargets: [],
  },
  TICKET_CREATE: {
    id: 'TICKET_CREATE',
    description: 'Create a ticket',
    requiredCapability: 'content.write', // or specific capability
    riskLevel: 'LOW',
    requiresSnapshot: false,
    requiresApproval: false,
    reversible: false,
    allowedStates: ['EXECUTING', 'COMPLETED', 'FAILED'],
    auditEvent: 'TICKET_CREATED',
    forbiddenTargets: [],
  },
  TICKET_UPDATE: {
    id: 'TICKET_UPDATE',
    description: 'Update a ticket',
    requiredCapability: 'content.write',
    riskLevel: 'LOW',
    requiresSnapshot: true,
    requiresApproval: false,
    reversible: true,
    allowedStates: ['EXECUTING', 'COMPLETED', 'FAILED', 'ROLLBACK_IN_PROGRESS', 'ROLLED_BACK'],
    auditEvent: 'TICKET_UPDATED',
    forbiddenTargets: [],
  },
  GIT_BRANCH_CREATE: {
    id: 'GIT_BRANCH_CREATE',
    description: 'Create a Git branch',
    requiredCapability: 'github.branch.create',
    riskLevel: 'MEDIUM',
    requiresSnapshot: false, // Snapshotting git state isn't handled via regular snapshot
    requiresApproval: false,
    reversible: false,
    allowedStates: ['BRANCH_CREATED', 'FAILED', 'BLOCKED'],
    auditEvent: 'GIT_BRANCH_CREATED',
    forbiddenTargets: ['main', 'master'],
  },
  GIT_COMMIT: {
    id: 'GIT_COMMIT',
    description: 'Commit to a Git branch',
    requiredCapability: 'github.commit',
    riskLevel: 'MEDIUM',
    requiresSnapshot: false,
    requiresApproval: false,
    reversible: false,
    allowedStates: ['COMMITTED', 'FAILED', 'BLOCKED'],
    auditEvent: 'GIT_COMMITTED',
    forbiddenTargets: ['main', 'master'],
  },
  GIT_PUSH_FEATURE: {
    id: 'GIT_PUSH_FEATURE',
    description: 'Push a feature branch',
    requiredCapability: 'github.push.feature',
    riskLevel: 'HIGH',
    requiresSnapshot: false,
    requiresApproval: false, // Could require approval depending on policy, but usually PR requires it
    reversible: false,
    allowedStates: ['PUSHED', 'FAILED', 'BLOCKED'],
    auditEvent: 'GIT_PUSHED_FEATURE',
    forbiddenTargets: ['main', 'master'],
  },
  GITHUB_PR_CREATE: {
    id: 'GITHUB_PR_CREATE',
    description: 'Create a PR on GitHub',
    requiredCapability: 'github.pr.create',
    riskLevel: 'HIGH',
    requiresSnapshot: false,
    requiresApproval: false,
    reversible: false,
    allowedStates: ['PR_CREATED', 'FAILED', 'BLOCKED'],
    auditEvent: 'GITHUB_PR_CREATED',
    forbiddenTargets: [],
  },
  GITHUB_PR_READ: {
    id: 'GITHUB_PR_READ',
    description: 'Read PR status',
    requiredCapability: 'github.read',
    riskLevel: 'LOW',
    requiresSnapshot: false,
    requiresApproval: false,
    reversible: false,
    allowedStates: ['EXECUTING', 'COMPLETED', 'FAILED'],
    auditEvent: 'GITHUB_PR_READ',
    forbiddenTargets: [],
  },
  CI_READ: {
    id: 'CI_READ',
    description: 'Read CI status',
    requiredCapability: 'github.read',
    riskLevel: 'LOW',
    requiresSnapshot: false,
    requiresApproval: false,
    reversible: false,
    allowedStates: ['EXECUTING', 'COMPLETED', 'FAILED'],
    auditEvent: 'CI_READ',
    forbiddenTargets: [],
  },
  AI_ANALYSIS: {
    id: 'AI_ANALYSIS',
    description: 'Run AI analysis',
    requiredCapability: 'qa.run', // map to existing capability
    riskLevel: 'LOW',
    requiresSnapshot: false,
    requiresApproval: false,
    reversible: false,
    allowedStates: ['EXECUTING', 'COMPLETED', 'FAILED'],
    auditEvent: 'AI_ANALYZED',
    forbiddenTargets: [],
  },
  AI_REVIEW: {
    id: 'AI_REVIEW',
    description: 'Run AI review on PR',
    requiredCapability: 'qa.run',
    riskLevel: 'LOW',
    requiresSnapshot: false,
    requiresApproval: false,
    reversible: false,
    allowedStates: ['AI_REVIEW', 'WAITING_MERGE_APPROVAL', 'FAILED'],
    auditEvent: 'AI_REVIEWED',
    forbiddenTargets: [],
  },
  VPS_READ: {
    id: 'VPS_READ',
    description: 'Read VPS state',
    requiredCapability: 'vps.read',
    riskLevel: 'LOW',
    requiresSnapshot: false,
    requiresApproval: false,
    reversible: false,
    allowedStates: ['EXECUTING', 'COMPLETED', 'FAILED'],
    auditEvent: 'VPS_READ',
    forbiddenTargets: [],
  },
  DEPLOY: {
    id: 'DEPLOY',
    description: 'Deploy to production',
    requiredCapability: 'deploy.production',
    riskLevel: 'CRITICAL',
    requiresSnapshot: true,
    requiresApproval: true,
    reversible: true,
    allowedStates: ['DEPLOYING', 'DEPLOYED', 'FAILED', 'BLOCKED'],
    auditEvent: 'DEPLOYED',
    forbiddenTargets: [],
  },
  ROLLBACK: {
    id: 'ROLLBACK',
    description: 'Rollback a previous deployment or mutation',
    requiredCapability: 'deploy.production',
    riskLevel: 'HIGH',
    requiresSnapshot: false,
    requiresApproval: true,
    reversible: false,
    allowedStates: ['ROLLBACK_WINDOW', 'ROLLED_BACK', 'FAILED', 'BLOCKED'],
    auditEvent: 'ROLLED_BACK',
    forbiddenTargets: [],
  },
  MERGE_MAIN: {
    id: 'MERGE_MAIN',
    description: 'Merge PR to main',
    requiredCapability: 'github.push.feature', // Assuming merging requires push access to main, usually we'd have github.merge
    riskLevel: 'CRITICAL',
    requiresSnapshot: true,
    requiresApproval: true,
    reversible: false, // Merges are hard to reverse cleanly automatically
    allowedStates: ['MERGED', 'FAILED', 'BLOCKED'],
    auditEvent: 'MERGED_TO_MAIN',
    forbiddenTargets: [],
  }
};
