import dotenv from 'dotenv';
dotenv.config();

import { prisma, isPrismaAvailable } from '../src/db/prisma';
import { dbStore } from '../src/services/dbStore';
import { ensureSuperAdminAccount } from '../src/services/seedService';
import { runHelpNewsSeed } from "./seed-help-news";

export const realSubjektyData = [
  // --- HLAVNÍ MĚSTO PRAHA ---
  {
    type: 'SOUD',
    name: 'Obvodní soud pro Prahu 1',
    titleBefore: null,
    position: 'Opatrovnický úsek',
    institution: 'Obvodní soud',
    city: 'Praha',
    region: 'Hlavní město Praha',
    address: 'Ovocný trh 587/14, 110 00 Praha 1',
    email: 'podatelna@osoud.pha1.justice.cz',
    phone: '+420 221 093 111',
    website: 'https://www.justice.cz',
    isVerified: true,
  },
  {
    type: 'SOUD',
    name: 'Obvodní soud pro Prahu 4',
    titleBefore: null,
    position: 'Opatrovnické oddělení',
    institution: 'Obvodní soud',
    city: 'Praha',
    region: 'Hlavní město Praha',
    address: '28. pluku 1533/29b, 100 83 Praha 10',
    email: 'podatelna@osoud.pha4.justice.cz',
    phone: '+420 221 553 111',
    website: 'https://www.justice.cz',
    isVerified: true,
  },
  {
    type: 'OSPOD',
    name: 'OSPOD ÚMČ Praha 1',
    titleBefore: null,
    position: 'Oddělení sociálně-právní ochrany dětí',
    institution: 'Úřad městské části Praha 1',
    city: 'Praha',
    region: 'Hlavní město Praha',
    address: 'Vodičkova 32, 115 68 Praha 1',
    email: 'posta@praha1.cz',
    phone: '+420 221 097 111',
    website: 'https://www.praha1.cz',
    isVerified: true,
  },
  {
    type: 'ZNALEC',
    name: 'Marie Svobodová',
    titleBefore: 'PhDr.',
    position: 'Soudní znalec - pedopsychologie a klinická psychologie',
    institution: 'Zkušebna a psychologická praxe Praha',
    city: 'Praha',
    region: 'Hlavní město Praha',
    address: 'Karlovo nám. 317/5, 120 00 Praha 2',
    email: 'svobodova.znalec@praha-psychologie.cz',
    phone: '+420 603 123 456',
    website: 'https://www.psychologie-praha.cz',
    isVerified: true,
  },
  {
    type: 'ZNALEC',
    name: 'Petr Dvořák',
    titleBefore: 'MUDr.',
    position: 'Soudní znalec v oboru psychiatrie, specializace dětská psychiatrie',
    institution: 'Psychiatrická klinika',
    city: 'Praha',
    region: 'Hlavní město Praha',
    address: 'Ke Karlovu 11, 120 00 Praha 2',
    email: 'dvorak.psychiatr@fnv.cz',
    phone: '+420 224 965 300',
    website: 'https://www.lf1.cuni.cz',
    isVerified: true,
  },
  {
    type: 'ADVOKAT',
    name: 'Tomáš Novotný',
    titleBefore: 'JUDr.',
    position: 'Advokát se zaměřením na rodinné právo a střídavou péči',
    institution: 'Advokátní kancelář Novotný & Partners',
    city: 'Praha',
    region: 'Hlavní město Praha',
    address: 'Václavské nám. 832/19, 110 00 Praha 1',
    email: 'tomas.novotny@ak-novotny.cz',
    phone: '+420 224 235 678',
    website: 'https://www.ak-novotny.cz',
    isVerified: true,
  },
  {
    type: 'PORADNA_CHARITA',
    name: 'Centrum LOCIKA, z.ú.',
    titleBefore: null,
    position: 'Centrum pro děti ohrožené domácím násilím a konfliktním rozvodem',
    institution: 'LOCIKA z.ú.',
    city: 'Praha',
    region: 'Hlavní město Praha',
    address: 'U Průhonu 1588/12, 170 00 Praha 7',
    email: 'info@centrumlocika.cz',
    phone: '+420 734 441 233',
    website: 'https://www.centrumlocika.cz',
    isVerified: true,
  },

  // --- STŘEDOČESKÝ KRAJ ---
  {
    type: 'SOUD',
    name: 'Okresní soud v Kladně',
    titleBefore: null,
    position: 'Opatrovnický úsek',
    institution: 'Okresní soud',
    city: 'Kladno',
    region: 'Středočeský kraj',
    address: 'Cyrila Boudy 2954, 272 59 Kladno',
    email: 'podatelna@osoud.kladno.justice.cz',
    phone: '+420 312 604 111',
    website: 'https://www.justice.cz',
    isVerified: true,
  },
  {
    type: 'OSPOD',
    name: 'OSPOD Magistrátu města Kladna',
    titleBefore: null,
    position: 'Oddělení sociálně-právní ochrany dětí',
    institution: 'Magistrát města Kladna',
    city: 'Kladno',
    region: 'Středočeský kraj',
    address: 'nám. Starosty Pavla 44, 272 52 Kladno',
    email: 'posta@mestokladno.cz',
    phone: '+420 312 604 333',
    website: 'https://www.mestokladno.cz',
    isVerified: true,
  },
  {
    type: 'ZNALEC',
    name: 'Jana Veselá',
    titleBefore: 'PhDr.',
    position: 'Soudní znalec - klinická psychologie dětí a mládeže',
    institution: 'Psychologická ordinace Středočeský kraj',
    city: 'Kladno',
    region: 'Středočeský kraj',
    address: 'Havlíčkova 123, 272 01 Kladno',
    email: 'vesela.znalec@psychologie-kladno.cz',
    phone: '+420 312 234 567',
    website: 'https://www.psychologie-kladno.cz',
    isVerified: true,
  },
  {
    type: 'ADVOKAT',
    name: 'Martin Procházka',
    titleBefore: 'JUDr.',
    position: 'Advokát pro rodinné právo a opatrovnické spory',
    institution: 'AK Procházka & spol.',
    city: 'Mladá Boleslav',
    region: 'Středočeský kraj',
    address: 'Komenského nám. 61, 293 01 Mladá Boleslav',
    email: 'martin.prochazka@ak-mb.cz',
    phone: '+420 326 732 111',
    website: 'https://www.ak-mb.cz',
    isVerified: true,
  },
  {
    type: 'PORADNA_CHARITA',
    name: 'Poradna pro rodinu Středočeského kraje',
    titleBefore: null,
    position: 'Manželské a rodinné poradenství, mediace',
    institution: 'Příspěvková organizace',
    city: 'Kladno',
    region: 'Středočeský kraj',
    address: 'Třída Československé armády 450, 272 01 Kladno',
    email: 'poradna.kladno@sck.cz',
    phone: '+420 312 245 889',
    website: 'https://www.poradna-stredoceska.cz',
    isVerified: true,
  },

  // --- JIHOČESKÝ KRAJ ---
  {
    type: 'SOUD',
    name: 'Okresní soud v Českých Budějovicích',
    titleBefore: null,
    position: 'Opatrovnické oddělení',
    institution: 'Okresní soud',
    city: 'České Budějovice',
    region: 'Jihočeský kraj',
    address: 'Lidická tř. 132/20, 370 01 České Budějovice',
    email: 'podatelna@osoud.cbu.justice.cz',
    phone: '+420 386 798 111',
    website: 'https://www.justice.cz',
    isVerified: true,
  },
  {
    type: 'OSPOD',
    name: 'OSPOD Magistrátu města České Budějovice',
    titleBefore: null,
    position: 'Oddělení sociálně-právní ochrany dětí',
    institution: 'Magistrát města České Budějovice',
    city: 'České Budějovice',
    region: 'Jihočeský kraj',
    address: 'Nám. Přemysla Otakara II. 1/1, 370 92 České Budějovice',
    email: 'podatelna@c-budejovice.cz',
    phone: '+420 386 801 111',
    website: 'https://www.c-budejovice.cz',
    isVerified: true,
  },
  {
    type: 'ZNALEC',
    name: 'Alena Malá',
    titleBefore: 'PhDr.',
    position: 'Soudní znalec - pedopsychologie',
    institution: 'Poradenské centrum Jihočeský kraj',
    city: 'České Budějovice',
    region: 'Jihočeský kraj',
    address: 'Na Sadech 24, 370 01 České Budějovice',
    email: 'mala.znalec@cb-psychologie.cz',
    phone: '+420 387 222 333',
    website: 'https://www.cb-psychologie.cz',
    isVerified: true,
  },
  {
    type: 'ADVOKAT',
    name: 'Petr Havlíček',
    titleBefore: 'Mgr.',
    position: 'Advokát - specializace na výživné a péči o děti',
    institution: 'AK Havlíček',
    city: 'České Budějovice',
    region: 'Jihočeský kraj',
    address: 'Kněžská 19, 370 01 České Budějovice',
    email: 'petr.havlicek@ak-cb.cz',
    phone: '+420 387 311 444',
    website: 'https://www.ak-cb.cz',
    isVerified: true,
  },
  {
    type: 'PORADNA_CHARITA',
    name: 'Krizové centrum pro děti a rodinu v Jihočeském kraji',
    titleBefore: null,
    position: 'Krizová intervence, psychologie',
    institution: 'Krizové centrum ČB',
    city: 'České Budějovice',
    region: 'Jihočeský kraj',
    address: 'Klasická 8, 370 01 České Budějovice',
    email: 'krizovecentrum@krizovecentrumcb.cz',
    phone: '+420 387 313 013',
    website: 'https://www.krizovecentrumcb.cz',
    isVerified: true,
  },

  // --- PLZEŇSKÝ KRAJ ---
  {
    type: 'SOUD',
    name: 'Okresní soud Plzeň-město',
    titleBefore: null,
    position: 'Opatrovnický úsek',
    institution: 'Okresní soud',
    city: 'Plzeň',
    region: 'Plzeňský kraj',
    address: 'Nádražní 587/21, 306 17 Plzeň',
    email: 'podatelna@osoud.plzm.justice.cz',
    phone: '+420 377 868 111',
    website: 'https://www.justice.cz',
    isVerified: true,
  },
  {
    type: 'OSPOD',
    name: 'OSPOD Magistrátu města Plzně',
    titleBefore: null,
    position: 'Oddělení sociálně-právní ochrany dětí',
    institution: 'Magistrát města Plzně',
    city: 'Plzeň',
    region: 'Plzeňský kraj',
    address: 'Martinská 2, 306 32 Plzeň',
    email: 'posta@plzen.eu',
    phone: '+420 378 031 111',
    website: 'https://www.plzen.eu',
    isVerified: true,
  },
  {
    type: 'ZNALEC',
    name: 'Karel Šimůnek',
    titleBefore: 'PhDr.',
    position: 'Soudní znalec v oboru psychologie dětí',
    institution: 'Psychologická praxe Plzeň',
    city: 'Plzeň',
    region: 'Plzeňský kraj',
    address: 'Americká 42, 301 00 Plzeň',
    email: 'simunek.znalec@plzen-psychologie.cz',
    phone: '+420 377 234 888',
    website: 'https://www.plzen-psychologie.cz',
    isVerified: true,
  },
  {
    type: 'ADVOKAT',
    name: 'Lenka Kučerová',
    titleBefore: 'JUDr.',
    position: 'Advokátka pro rodinné právo',
    institution: 'AK Kučerová Plzeň',
    city: 'Plzeň',
    region: 'Plzeňský kraj',
    address: 'Sady 5. května 24, 301 00 Plzeň',
    email: 'lenka.kucerova@ak-plzen.cz',
    phone: '+420 377 456 789',
    website: 'https://www.ak-plzen.cz',
    isVerified: true,
  },
  {
    type: 'PORADNA_CHARITA',
    name: 'Diecézní charita Plzeň - Rodinná poradna',
    titleBefore: null,
    position: 'Odborné sociální poradenství a rodinná terapie',
    institution: 'Diecézní charita Plzeň',
    city: 'Plzeň',
    region: 'Plzeňský kraj',
    address: 'Cihlářská 30, 301 00 Plzeň',
    email: 'poradna@dchp.cz',
    phone: '+420 377 444 555',
    website: 'https://www.dchp.cz',
    isVerified: true,
  },

  // --- KARLOVARSKÝ KRAJ ---
  {
    type: 'SOUD',
    name: 'Okresní soud v Karlových Varech',
    titleBefore: null,
    position: 'Opatrovnický úsek',
    institution: 'Okresní soud',
    city: 'Karlovy Vary',
    region: 'Karlovarský kraj',
    address: 'Moskevská 1009/17, 360 01 Karlovy Vary',
    email: 'podatelna@osoud.kva.justice.cz',
    phone: '+420 353 301 111',
    website: 'https://www.justice.cz',
    isVerified: true,
  },
  {
    type: 'OSPOD',
    name: 'OSPOD Magistrátu města Karlovy Vary',
    titleBefore: null,
    position: 'Oddělení sociálně-právní ochrany dětí',
    institution: 'Magistrát města Karlovy Vary',
    city: 'Karlovy Vary',
    region: 'Karlovarský kraj',
    address: 'Moskevská 21, 361 20 Karlovy Vary',
    email: 'podatelna@mmkv.cz',
    phone: '+420 353 152 111',
    website: 'https://www.karlovyvary.cz',
    isVerified: true,
  },
  {
    type: 'ZNALEC',
    name: 'Zuzana Nováková',
    titleBefore: 'PhDr.',
    position: 'Soudní znalec - dětská psychologie',
    institution: 'Psychologická poradna KV',
    city: 'Karlovy Vary',
    region: 'Karlovarský kraj',
    address: 'T. G. Masaryka 35, 360 01 Karlovy Vary',
    email: 'novakova.znalec@kv-psychologie.cz',
    phone: '+420 353 222 111',
    website: 'https://www.kv-psychologie.cz',
    isVerified: true,
  },
  {
    type: 'ADVOKAT',
    name: 'Jan Svoboda',
    titleBefore: 'Mgr.',
    position: 'Advokát se zaměřením na opatrovnické spory',
    institution: 'AK Svoboda Karlovy Vary',
    city: 'Karlovy Vary',
    region: 'Karlovarský kraj',
    address: 'I. P. Pavlova 8, 360 01 Karlovy Vary',
    email: 'jan.svoboda@ak-kv.cz',
    phone: '+420 353 587 999',
    website: 'https://www.ak-kv.cz',
    isVerified: true,
  },
  {
    type: 'PORADNA_CHARITA',
    name: 'Oblastní charita Karlovy Vary - Poradna',
    titleBefore: null,
    position: 'Krizová pomoc a rodinné poradenství',
    institution: 'Charita Karlovy Vary',
    city: 'Karlovy Vary',
    region: 'Karlovarský kraj',
    address: 'Závodní 353/88, 360 06 Karlovy Vary',
    email: 'info@karlovyvary.charita.cz',
    phone: '+420 353 311 222',
    website: 'https://www.karlovyvary.charita.cz',
    isVerified: true,
  },

  // --- ÚSTECKÝ KRAJ ---
  {
    type: 'SOUD',
    name: 'Okresní soud v Ústí nad Labem',
    titleBefore: null,
    position: 'Opatrovnické oddělení',
    institution: 'Okresní soud',
    city: 'Ústí nad Labem',
    region: 'Ústecký kraj',
    address: 'Kramoly 641/31, 400 01 Ústí nad Labem',
    email: 'podatelna@osoud.unl.justice.cz',
    phone: '+420 475 247 111',
    website: 'https://www.justice.cz',
    isVerified: true,
  },
  {
    type: 'OSPOD',
    name: 'OSPOD Magistrátu města Ústí nad Labem',
    titleBefore: null,
    position: 'Oddělení sociálně-právní ochrany dětí',
    institution: 'Magistrát města Ústí nad Labem',
    city: 'Ústí nad Labem',
    region: 'Ústecký kraj',
    address: 'Velká Hradební 2336/8, 400 01 Ústí nad Labem',
    email: 'podatelna@mestecko.cz',
    phone: '+420 475 271 111',
    website: 'https://www.usti-nad-labem.cz',
    isVerified: true,
  },
  {
    type: 'ZNALEC',
    name: 'Hana Kučerová',
    titleBefore: 'PhDr.',
    position: 'Soudní znalec - klinická psychologie a pedopsychologie',
    institution: 'Znalec Ústí nad Labem',
    city: 'Ústí nad Labem',
    region: 'Ústecký kraj',
    address: 'Bratislavská 4, 400 01 Ústí nad Labem',
    email: 'kucerova.znalec@ul-psychologie.cz',
    phone: '+420 475 512 345',
    website: 'https://www.ul-psychologie.cz',
    isVerified: true,
  },
  {
    type: 'ADVOKAT',
    name: 'Radek Veselý',
    titleBefore: 'JUDr.',
    position: 'Advokát - rodinné právo a ochrana práv otců',
    institution: 'AK Veselý Ústí n. L.',
    city: 'Ústí nad Labem',
    region: 'Ústecký kraj',
    address: 'Dlouhá 1/12, 400 01 Ústí nad Labem',
    email: 'radek.vesely@ak-ul.cz',
    phone: '+420 475 210 987',
    website: 'https://www.ak-ul.cz',
    isVerified: true,
  },
  {
    type: 'PORADNA_CHARITA',
    name: 'Poradna pro rodinu Ústí nad Labem',
    titleBefore: null,
    position: 'Odborné rodinné a manželské poradenství',
    institution: 'Poradna Ústí p.o.',
    city: 'Ústí nad Labem',
    region: 'Ústecký kraj',
    address: 'Sociální péče 3316/12, 400 11 Ústí nad Labem',
    email: 'poradna.ul@volny.cz',
    phone: '+420 475 600 400',
    website: 'https://www.poradna-ul.cz',
    isVerified: true,
  },

  // --- LIBERECKÝ KRAJ ---
  {
    type: 'SOUD',
    name: 'Okresní soud v Liberci',
    titleBefore: null,
    position: 'Opatrovnický úsek',
    institution: 'Okresní soud',
    city: 'Liberec',
    region: 'Liberecký kraj',
    address: 'U Soudu 540/3, 460 01 Liberec',
    email: 'podatelna@osoud.lbc.justice.cz',
    phone: '+420 485 221 111',
    website: 'https://www.justice.cz',
    isVerified: true,
  },
  {
    type: 'OSPOD',
    name: 'OSPOD Magistrátu města Liberec',
    titleBefore: null,
    position: 'Oddělení sociálně-právní ochrany dětí',
    institution: 'Magistrát města Liberec',
    city: 'Liberec',
    region: 'Liberecký kraj',
    address: 'Nám. Dr. E. Beneše 1/1, 460 59 Liberec',
    email: 'info@magistrat.liberec.cz',
    phone: '+420 485 243 111',
    website: 'https://www.liberec.cz',
    isVerified: true,
  },
  {
    type: 'ZNALEC',
    name: 'Věra Horáková',
    titleBefore: 'PhDr.',
    position: 'Soudní znalec - pedopsychologie Liberec',
    institution: 'Psychologická kancelář Liberec',
    city: 'Liberec',
    region: 'Liberecký kraj',
    address: 'Pražská 15, 460 01 Liberec',
    email: 'horakova.znalec@liberec-psychologie.cz',
    phone: '+420 485 311 222',
    website: 'https://www.liberec-psychologie.cz',
    isVerified: true,
  },
  {
    type: 'ADVOKAT',
    name: 'David Král',
    titleBefore: 'Mgr.',
    position: 'Advokát pro občanské a rodinné právo',
    institution: 'AK Král Liberec',
    city: 'Liberec',
    region: 'Liberecký kraj',
    address: 'Moskevská 26, 460 01 Liberec',
    email: 'david.kral@ak-liberec.cz',
    phone: '+420 485 100 333',
    website: 'https://www.ak-liberec.cz',
    isVerified: true,
  },
  {
    type: 'PORADNA_CHARITA',
    name: 'Centrum intervenční a sociální pomoci Liberec',
    titleBefore: null,
    position: 'Krizová pomoc a rodinné poradenství',
    institution: 'CISP Liberec',
    city: 'Liberec',
    region: 'Liberecký kraj',
    address: 'U Kúpie 5, 460 01 Liberec',
    email: 'cisp@liberec-pomoc.cz',
    phone: '+420 485 456 789',
    website: 'https://www.liberec-pomoc.cz',
    isVerified: true,
  },

  // --- KRÁLOVÉHRADECKÝ KRAJ ---
  {
    type: 'SOUD',
    name: 'Okresní soud v Hradci Králové',
    titleBefore: null,
    position: 'Opatrovnické oddělení',
    institution: 'Okresní soud',
    city: 'Hradec Králové',
    region: 'Královéhradecký kraj',
    address: 'Ignáta Herrmanna 227, 501 28 Hradec Králové',
    email: 'podatelna@osoud.hrk.justice.cz',
    phone: '+420 495 010 111',
    website: 'https://www.justice.cz',
    isVerified: true,
  },
  {
    type: 'OSPOD',
    name: 'OSPOD Magistrátu města Hradec Králové',
    titleBefore: null,
    position: 'Oddělení sociálně-právní ochrany dětí',
    institution: 'Magistrát města Hradec Králové',
    city: 'Hradec Králové',
    region: 'Královéhradecký kraj',
    address: 'Čs. armády 408, 502 00 Hradec Králové',
    email: 'posta@mmhk.cz',
    phone: '+420 495 707 111',
    website: 'https://www.hradeckralove.org',
    isVerified: true,
  },
  {
    type: 'ZNALEC',
    name: 'Marcela Tichá',
    titleBefore: 'PhDr.',
    position: 'Soudní znalec - dětská psychologie',
    institution: 'Znalec Hradec Králové',
    city: 'Hradec Králové',
    region: 'Královéhradecký kraj',
    address: 'Velké náměstí 35, 500 03 Hradec Králové',
    email: 'ticha.znalec@hk-psychologie.cz',
    phone: '+420 495 511 223',
    website: 'https://www.hk-psychologie.cz',
    isVerified: true,
  },
  {
    type: 'ADVOKAT',
    name: 'Pavel Soukup',
    titleBefore: 'JUDr.',
    position: 'Advokát se zaměřením na rozvody a péči o děti',
    institution: 'AK Soukup Hradec Králové',
    city: 'Hradec Králové',
    region: 'Královéhradecký kraj',
    address: 'Gočárova třída 1221, 500 02 Hradec Králové',
    email: 'pavel.soukup@ak-hk.cz',
    phone: '+420 495 822 111',
    website: 'https://www.ak-hk.cz',
    isVerified: true,
  },
  {
    type: 'PORADNA_CHARITA',
    name: 'Diecézní charita Hradec Králové - Rodinná poradna',
    titleBefore: null,
    position: 'Poradenství v oblasti rodinných a majetkových sporů',
    institution: 'Diecézní charita HK',
    city: 'Hradec Králové',
    region: 'Královéhradecký kraj',
    address: 'Komenského 266, 500 03 Hradec Králové',
    email: 'poradna@hk.charita.cz',
    phone: '+420 495 512 789',
    website: 'https://www.hk.charita.cz',
    isVerified: true,
  },

  // --- PARDUBICKÝ KRAJ ---
  {
    type: 'SOUD',
    name: 'Okresní soud v Pardubicích',
    titleBefore: null,
    position: 'Opatrovnický úsek',
    institution: 'Okresní soud',
    city: 'Pardubice',
    region: 'Pardubický kraj',
    address: 'Na Tříslovisšti 2034, 530 02 Pardubice',
    email: 'podatelna@osoud.pce.justice.cz',
    phone: '+420 466 023 111',
    website: 'https://www.justice.cz',
    isVerified: true,
  },
  {
    type: 'OSPOD',
    name: 'OSPOD Magistrátu města Pardubic',
    titleBefore: null,
    position: 'Oddělení sociálně-právní ochrany dětí',
    institution: 'Magistrát města Pardubic',
    city: 'Pardubice',
    region: 'Pardubický kraj',
    address: 'Pernštýnské náměstí 1, 530 21 Pardubice',
    email: 'posta@mmp.cz',
    phone: '+420 466 859 111',
    website: 'https://www.pardubice.eu',
    isVerified: true,
  },
  {
    type: 'OSPOD',
    name: 'Městský úřad Přelouč - Odbor sociálních věcí a zdravotnictví',
    titleBefore: null,
    position: 'OSPOD Přelouč',
    institution: 'Městský úřad Přelouč',
    city: 'Přelouč',
    region: 'Pardubický kraj',
    address: 'Československé armády 1565, 535 33 Přelouč',
    email: 'podatelna@muprelouc.cz',
    phone: '+420 469 605 111',
    website: 'https://www.muprelouc.cz',
    isVerified: true,
  },
  {
    type: 'ZNALEC',
    name: 'Jaroslav Beneš',
    titleBefore: 'PhDr.',
    position: 'Soudní znalec - pedopsychologie a diagnostika',
    institution: 'Psychologická praxe Pardubice',
    city: 'Pardubice',
    region: 'Pardubický kraj',
    address: 'Smilova 356, 530 02 Pardubice',
    email: 'benes.znalec@pce-psychologie.cz',
    phone: '+420 466 512 333',
    website: 'https://www.pce-psychologie.cz',
    isVerified: true,
  },
  {
    type: 'ADVOKAT',
    name: 'Roman Kovář',
    titleBefore: 'JUDr.',
    position: 'Advokát pro rodinné právo a zastupování v opatrovnických řízeních',
    institution: 'AK Kovář Pardubice',
    city: 'Pardubice',
    region: 'Pardubický kraj',
    address: 'Třída Míru 92, 530 02 Pardubice',
    email: 'roman.kovar@ak-pardubice.cz',
    phone: '+420 466 312 456',
    website: 'https://www.ak-pardubice.cz',
    isVerified: true,
  },
  {
    type: 'PORADNA_CHARITA',
    name: 'Krizové centrum Pardubice',
    titleBefore: null,
    position: 'Krizová intervence a rodinné poradenství',
    institution: 'SKP CENTRUM, o.p.s.',
    city: 'Pardubice',
    region: 'Pardubický kraj',
    address: 'Erno Košťála 981, 530 12 Pardubice',
    email: 'krizovecentrum@skpcentrum.cz',
    phone: '+420 466 303 123',
    website: 'https://www.skpcentrum.cz',
    isVerified: true,
  },

  // --- KRAJ VYSOČINA ---
  {
    type: 'SOUD',
    name: 'Okresní soud v Jihlavě',
    titleBefore: null,
    position: 'Opatrovnické oddělení',
    institution: 'Okresní soud',
    city: 'Jihlava',
    region: 'Kraj Vysočina',
    address: 'Husova 1639/47, 586 01 Jihlava',
    email: 'podatelna@osoud.jhl.justice.cz',
    phone: '+420 567 101 111',
    website: 'https://www.justice.cz',
    isVerified: true,
  },
  {
    type: 'OSPOD',
    name: 'OSPOD Magistrátu města Jihlavy',
    titleBefore: null,
    position: 'Oddělení sociálně-právní ochrany dětí',
    institution: 'Magistrát města Jihlavy',
    city: 'Jihlava',
    region: 'Kraj Vysočina',
    address: 'Masarykovo nám. 1, 586 01 Jihlava',
    email: 'posta@jihlava-city.cz',
    phone: '+420 565 593 111',
    website: 'https://www.jihlava.cz',
    isVerified: true,
  },
  {
    type: 'ZNALEC',
    name: 'Eva Procházková',
    titleBefore: 'PhDr.',
    position: 'Soudní znalec - dětská a klinická psychologie',
    institution: 'Psychologická poradna Vysočina',
    city: 'Jihlava',
    region: 'Kraj Vysočina',
    address: 'Havlíčkova 28, 586 01 Jihlava',
    email: 'prochazkova.znalec@vysočina-psychologie.cz',
    phone: '+420 567 222 555',
    website: 'https://www.vysočina-psychologie.cz',
    isVerified: true,
  },
  {
    type: 'ADVOKAT',
    name: 'Aleš Novák',
    titleBefore: 'Mgr.',
    position: 'Advokát se zaměřením na opatrovnické právo',
    institution: 'AK Novák Jihlava',
    city: 'Jihlava',
    region: 'Kraj Vysočina',
    address: 'Křížová 12, 586 01 Jihlava',
    email: 'ales.novak@ak-jihlava.cz',
    phone: '+420 567 333 777',
    website: 'https://www.ak-jihlava.cz',
    isVerified: true,
  },
  {
    type: 'PORADNA_CHARITA',
    name: 'Poradna pro rodinu Vysočina',
    titleBefore: null,
    position: 'Manželské a rodinné poradenství, krizová pomoc',
    institution: 'Poradna Vysočina p.o.',
    city: 'Jihlava',
    region: 'Kraj Vysočina',
    address: 'Tolstého 15, 586 01 Jihlava',
    email: 'poradna@poradnavysocina.cz',
    phone: '+420 567 444 888',
    website: 'https://www.poradnavysocina.cz',
    isVerified: true,
  },

  // --- JIHOMORAVSKÝ KRAJ ---
  {
    type: 'SOUD',
    name: 'Městský soud v Brně',
    titleBefore: null,
    position: 'Opatrovnický úsek',
    institution: 'Městský soud',
    city: 'Brno',
    region: 'Jihomoravský kraj',
    address: 'Polní 994/9, 608 01 Brno',
    email: 'podatelna@msoud.brn.justice.cz',
    phone: '+420 546 511 111',
    website: 'https://www.justice.cz',
    isVerified: true,
  },
  {
    type: 'OSPOD',
    name: 'OSPOD Magistrátu města Brna',
    titleBefore: null,
    position: 'Oddělení sociálně-právní ochrany dětí',
    institution: 'Magistrát města Brna',
    city: 'Brno',
    region: 'Jihomoravský kraj',
    address: 'Malinovského nám. 3, 601 67 Brno',
    email: 'posta@brno.cz',
    phone: '+420 542 171 111',
    website: 'https://www.brno.cz',
    isVerified: true,
  },
  {
    type: 'ZNALEC',
    name: 'Petr Říčan',
    titleBefore: 'prof. PhDr.',
    position: 'Soudní znalec - vývojová psychologie a rodinné vztahy',
    institution: 'Akademická psychologická poradna Brno',
    city: 'Brno',
    region: 'Jihomoravský kraj',
    address: 'Joštova 10, 602 00 Brno',
    email: 'rican.znalec@brno-znalci.cz',
    phone: '+420 542 321 987',
    website: 'https://www.brno-znalci.cz',
    isVerified: true,
  },
  {
    type: 'ADVOKAT',
    name: 'Hana Dvořáková',
    titleBefore: 'JUDr.',
    position: 'Advokátka pro rodinné právo',
    institution: 'AK Dvořáková Brno',
    city: 'Brno',
    region: 'Jihomoravský kraj',
    address: 'Masarykova 31, 602 00 Brno',
    email: 'hana.dvorakova@ak-brno.cz',
    phone: '+420 542 222 111',
    website: 'https://www.ak-brno.cz',
    isVerified: true,
  },
  {
    type: 'PORADNA_CHARITA',
    name: 'Centrum pro rodinu a sociální péči Brno',
    titleBefore: null,
    position: 'Rodinná mediace, poradenství a kurzy pro rodiče',
    institution: 'CRSP Brno',
    city: 'Brno',
    region: 'Jihomoravský kraj',
    address: 'Josefská 1, 602 00 Brno',
    email: 'crsp@crsp.cz',
    phone: '+420 542 211 860',
    website: 'https://www.crsp.cz',
    isVerified: true,
  },

  // --- OLOMOUCKÝ KRAJ ---
  {
    type: 'SOUD',
    name: 'Okresní soud v Olomouci',
    titleBefore: null,
    position: 'Opatrovnické oddělení',
    institution: 'Okresní soud',
    city: 'Olomouc',
    region: 'Olomoucký kraj',
    address: 'Tř. Svobody 685/16, 771 16 Olomouc',
    email: 'podatelna@osoud.olc.justice.cz',
    phone: '+420 585 512 111',
    website: 'https://www.justice.cz',
    isVerified: true,
  },
  {
    type: 'OSPOD',
    name: 'OSPOD Magistrátu města Olomouce',
    titleBefore: null,
    position: 'Oddělení sociálně-právní ochrany dětí',
    institution: 'Magistrát města Olomouce',
    city: 'Olomouc',
    region: 'Olomoucký kraj',
    address: 'Hynaisova 10, 779 11 Olomouc',
    email: 'podatelna@olomouc.eu',
    phone: '+420 585 513 111',
    website: 'https://www.olomouc.eu',
    isVerified: true,
  },
  {
    type: 'ZNALEC',
    name: 'Radka Svobodová',
    titleBefore: 'PhDr.',
    position: 'Soudní znalec - dětská psychologie',
    institution: 'Psychologická praxe Olomouc',
    city: 'Olomouc',
    region: 'Olomoucký kraj',
    address: 'Horní náměstí 5, 779 00 Olomouc',
    email: 'svobodova.znalec@olomouc-psychologie.cz',
    phone: '+420 585 223 444',
    website: 'https://www.olomouc-psychologie.cz',
    isVerified: true,
  },
  {
    type: 'ADVOKAT',
    name: 'Kamil Beneš',
    titleBefore: 'Mgr.',
    position: 'Advokát pro občanské a opatrovnické právo',
    institution: 'AK Beneš Olomouc',
    city: 'Olomouc',
    region: 'Olomoucký kraj',
    address: 'Pekařská 4, 779 00 Olomouc',
    email: 'kamil.benes@ak-olomouc.cz',
    phone: '+420 585 200 111',
    website: 'https://www.ak-olomouc.cz',
    isVerified: true,
  },
  {
    type: 'PORADNA_CHARITA',
    name: 'Charitní poradna Olomouc',
    titleBefore: null,
    position: 'Poradenství v obtížných životních situacích a rodinné spory',
    institution: 'Charita Olomouc',
    city: 'Olomouc',
    region: 'Olomoucký kraj',
    address: 'Wurmova 5, 779 00 Olomouc',
    email: 'poradna@olomouc.charita.cz',
    phone: '+420 585 225 333',
    website: 'https://www.olomouc.charita.cz',
    isVerified: true,
  },

  // --- ZLÍNSKÝ KRAJ ---
  {
    type: 'SOUD',
    name: 'Okresní soud ve Zlíně',
    titleBefore: null,
    position: 'Opatrovnický úsek',
    institution: 'Okresní soud',
    city: 'Zlín',
    region: 'Zlínský kraj',
    address: 'Dlouhá 100, 760 01 Zlín',
    email: 'podatelna@osoud.zln.justice.cz',
    phone: '+420 577 004 111',
    website: 'https://www.justice.cz',
    isVerified: true,
  },
  {
    type: 'OSPOD',
    name: 'OSPOD Magistrátu města Zlína',
    titleBefore: null,
    position: 'Oddělení sociálně-právní ochrany dětí',
    institution: 'Magistrát města Zlína',
    city: 'Zlín',
    region: 'Zlínský kraj',
    address: 'Náměstí Míru 12, 760 01 Zlín',
    email: 'podatelna@zlin.eu',
    phone: '+420 577 630 111',
    website: 'https://www.zlin.eu',
    isVerified: true,
  },
  {
    type: 'ZNALEC',
    name: 'Martina Vlková',
    titleBefore: 'PhDr.',
    position: 'Soudní znalec - klinická psychologie',
    institution: 'Psychologická ordinace Zlín',
    city: 'Zlín',
    region: 'Zlínský kraj',
    address: 'Gorkého 3456, 760 01 Zlín',
    email: 'vlkova.znalec@zlin-psychologie.cz',
    phone: '+420 577 211 444',
    website: 'https://www.zlin-psychologie.cz',
    isVerified: true,
  },
  {
    type: 'ADVOKAT',
    name: 'Stanislav Valenta',
    titleBefore: 'JUDr.',
    position: 'Advokát pro rodinné a opatrovnické právo',
    institution: 'AK Valenta Zlín',
    city: 'Zlín',
    region: 'Zlínský kraj',
    address: 'Rašínova 246, 760 01 Zlín',
    email: 'stanislav.valenta@ak-zlin.cz',
    phone: '+420 577 321 555',
    website: 'https://www.ak-zlin.cz',
    isVerified: true,
  },
  {
    type: 'PORADNA_CHARITA',
    name: 'Poradna pro rodinu Zlín',
    titleBefore: null,
    position: 'Manželské a rodinné poradenství, mediace',
    institution: 'Poradna Zlín p.o.',
    city: 'Zlín',
    region: 'Zlínský kraj',
    address: 'Sokolská 3060, 760 01 Zlín',
    email: 'poradna@poradnazlin.cz',
    phone: '+420 577 433 222',
    website: 'https://www.poradnazlin.cz',
    isVerified: true,
  },

  // --- MORAVSKOSLEZSKÝ KRAJ ---
  {
    type: 'SOUD',
    name: 'Okresní soud v Ostravě',
    titleBefore: null,
    position: 'Opatrovnické oddělení',
    institution: 'Okresní soud',
    city: 'Ostrava',
    region: 'Moravskoslezský kraj',
    address: 'U Soudu 6187/4, 708 00 Ostrava-Poruba',
    email: 'podatelna@osoud.ova.justice.cz',
    phone: '+420 596 972 111',
    website: 'https://www.justice.cz',
    isVerified: true,
  },
  {
    type: 'OSPOD',
    name: 'OSPOD Magistrátu města Ostravy',
    titleBefore: null,
    position: 'Oddělení sociálně-právní ochrany dětí',
    institution: 'Magistrát města Ostravy',
    city: 'Ostrava',
    region: 'Moravskoslezský kraj',
    address: 'Prokešovo náměstí 1803/8, 729 30 Ostrava',
    email: 'info@ostrava.cz',
    phone: '+420 599 444 444',
    website: 'https://www.ostrava.cz',
    isVerified: true,
  },
  {
    type: 'ZNALEC',
    name: 'Daniela Růžičková',
    titleBefore: 'PhDr.',
    position: 'Soudní znalec - pedopsychologie a soudní psychologie',
    institution: 'Znalec Ostrava',
    city: 'Ostrava',
    region: 'Moravskoslezský kraj',
    address: '28. října 150, 702 00 Ostrava',
    email: 'ruzickova.znalec@ostrava-psychologie.cz',
    phone: '+420 596 112 333',
    website: 'https://www.ostrava-psychologie.cz',
    isVerified: true,
  },
  {
    type: 'ZNALEC',
    name: 'Robert Horák',
    titleBefore: 'MUDr.',
    position: 'Soudní znalec - dětská psychiatrie',
    institution: 'Psychiatrická ambulance Ostrava',
    city: 'Ostrava',
    region: 'Moravskoslezský kraj',
    address: 'Varenská 51, 702 00 Ostrava',
    email: 'horak.znalec@detska-psychiatrie-ova.cz',
    phone: '+420 597 456 123',
    website: 'https://www.detska-psychiatrie-ova.cz',
    isVerified: true,
  },
  {
    type: 'ADVOKAT',
    name: 'Vít Černý',
    titleBefore: 'JUDr.',
    position: 'Advokát pro rodinné právo a ochranu zájmů dětí',
    institution: 'AK Černý Ostrava',
    city: 'Ostrava',
    region: 'Moravskoslezský kraj',
    address: 'Zámecká 14, 702 00 Ostrava',
    email: 'vit.cerny@ak-ostrava.cz',
    phone: '+420 596 222 111',
    website: 'https://www.ak-ostrava.cz',
    isVerified: true,
  },
  {
    type: 'PORADNA_CHARITA',
    name: 'Poradna pro rodinu Ostrava',
    titleBefore: null,
    position: 'Manželské a rodinné poradenství',
    institution: 'Poradna Ostrava p.o.',
    city: 'Ostrava',
    region: 'Moravskoslezský kraj',
    address: 'Jurečkova 19, 702 00 Ostrava',
    email: 'poradna@poradna-ostrava.cz',
    phone: '+420 596 133 444',
    website: 'https://www.poradna-ostrava.cz',
    isVerified: true,
  },
];

export async function runSeed() {
  console.log('[Prisma Seed] Spouštím kompletaci výchozích CMS a registračních dat...');

  try {
    // 0. Ujistit se o existenci účtu Super Admina a rolí
    await ensureSuperAdminAccount().catch(() => {});

    if (isPrismaAvailable()) {
      // 1. POLOŽKY NAVIGACE (7 kategorií, 33 modulů portálu + Domů)
      console.log('[Prisma Seed] Seedování položek navigace...');
      await prisma.navigationItem.deleteMany({}); // Vyčištění staré navigace

      // Samostatné tlačítko Domů
      await prisma.navigationItem.create({
        data: { id: 'nav-1', labelKey: 'Domů', url: '/', order: 1, target: '_self', isExternal: false },
      });

      const categoriesNav = [
        {
          id: 'cat-1',
          labelKey: '🚨 Krizová pomoc & Komunita',
          url: '#',
          order: 10,
          subItems: [
            { id: 'sub-1-1', labelKey: 'SOS plán', url: '/crisis', order: 11 },
            { id: 'sub-1-2', labelKey: 'Fórum', url: '/forum', order: 12 },
            { id: 'sub-1-3', labelKey: 'Příběhy', url: '/stories', order: 13 },
            { id: 'sub-1-4', labelKey: 'Memento', url: '/memento', order: 14 },
            { id: 'sub-1-5', labelKey: 'Právní poradna', url: '/advice', order: 15 },
            { id: 'sub-1-6', labelKey: 'Podpora', url: '/support', order: 16 },
          ],
        },
        {
          id: 'cat-2',
          labelKey: '⚖️ Opatrovnictví & Právo',
          url: '#',
          order: 20,
          subItems: [
            { id: 'sub-2-1', labelKey: 'Agenda', url: '/opatrovnicka-agenda', order: 21 },
            { id: 'sub-2-2', labelKey: 'Práva', url: '/rights', order: 22 },
            { id: 'sub-2-3', labelKey: 'Judikatura', url: '/judikatura', order: 23 },
            { id: 'sub-2-4', labelKey: 'Dokumenty', url: '/ke-stazeni', order: 24 },
            { id: 'sub-2-5', labelKey: 'Registr Subjektů', url: '/registr-subjektu', order: 25 },
          ],
        },
        {
          id: 'cat-3',
          labelKey: '🏛️ Státní data',
          url: '#',
          order: 30,
          subItems: [
            { id: 'sub-3-1', labelKey: 'e-Sbírka', url: '/state-laws', order: 31 },
            { id: 'sub-3-2', labelKey: 'Statistiky', url: '/state-statistics', order: 32 },
            { id: 'sub-3-3', labelKey: 'Databáze', url: '/pripadova-databaze', order: 33 },
          ],
        },
        {
          id: 'cat-4',
          labelKey: '🎓 Akademie',
          url: '#',
          order: 40,
          subItems: [
            { id: 'sub-4-1', labelKey: 'Studia', url: '/knihovna-studii', order: 41 },
            { id: 'sub-4-2', labelKey: 'Videotéka', url: '/videoteka', order: 42 },
            { id: 'sub-4-3', labelKey: 'Kvízy', url: '/vzdelavani', order: 43 },
            { id: 'sub-4-4', labelKey: 'Wiki', url: '/legal-wiki', order: 44 },
            { id: 'sub-4-5', labelKey: 'Zakladatel', url: '/cesta-zakladatele', order: 45 },
          ],
        },
        {
          id: 'cat-5',
          labelKey: '📂 Pracovna',
          url: '#',
          order: 50,
          subItems: [
            { id: 'sub-5-1', labelKey: 'Složka', url: '/user-portal', order: 51 },
            { id: 'sub-5-2', labelKey: 'Profil', url: '/profile', order: 52 },
            { id: 'sub-5-3', labelKey: 'CoParent', url: '/coparent-hub', order: 53 },
          ],
        },
        {
          id: 'cat-6',
          labelKey: '🤖 AI nástroje',
          url: '#',
          order: 60,
          subItems: [
            { id: 'sub-6-1', labelKey: 'Asistent', url: '/ai-assistant', order: 61 },
            { id: 'sub-6-2', labelKey: 'Průvodce', url: '/ai-guide', order: 62 },
            { id: 'sub-6-3', labelKey: 'Case manager', url: '/ai-case-manager', order: 63 },
            { id: 'sub-6-4', labelKey: 'Simulátor', url: '/plan-pece', order: 64 },
            { id: 'sub-6-5', labelKey: 'Formuláře', url: '/centrum-formularu', order: 65 },
          ],
        },
        {
          id: 'cat-7',
          labelKey: '🛠️ Systém',
          url: '#',
          order: 70,
          subItems: [
            { id: 'sub-7-1', labelKey: 'Novinky', url: '/news', order: 71 },
            { id: 'sub-7-2', labelKey: 'Hub', url: '/synthesis-hub', order: 72 },
            { id: 'sub-7-3', labelKey: 'AI admin', url: '/ai-admin', order: 73 },
            { id: 'sub-7-4', labelKey: 'Admin', url: '/admin', order: 74 },
            { id: 'sub-7-5', labelKey: 'Context', url: '/ai-context', order: 75 },
            { id: 'sub-7-6', labelKey: 'Nápověda', url: '/user-manual', order: 76 },
            { id: 'sub-7-7', labelKey: 'Architektura', url: '/sitemap', order: 77 },
          ],
        },
        {
          id: 'cat-8',
          labelKey: 'ℹ️ O projektu tatovacesta.cz',
          url: '#',
          order: 80,
          subItems: [
            { id: 'sub-8-1', labelKey: 'O nás', url: '/o-nas', order: 81 },
            { id: 'sub-8-2', labelKey: 'Kontakt', url: '/kontakt', order: 82 },
            { id: 'sub-8-3', labelKey: 'Sponzoři', url: '/sponzori', order: 83 },
            { id: 'sub-8-4', labelKey: 'Partneři', url: '/partneri', order: 84 },
          ],
        },
      ];

      for (const cat of categoriesNav) {
        const parent = await prisma.navigationItem.create({
          data: {
            id: cat.id,
            labelKey: cat.labelKey,
            url: cat.url,
            order: cat.order,
            target: '_self',
            isExternal: false,
          },
        });

        for (const sub of cat.subItems) {
          await prisma.navigationItem.create({
            data: {
              id: sub.id,
              labelKey: sub.labelKey,
              url: sub.url,
              order: sub.order,
              target: '_self',
              isExternal: false,
              parentId: parent.id,
            },
          });
        }
      }

      // 2. STRÁNKY (`Page` & `PageSection`)
      console.log('[Prisma Seed] Seedování základních stránek a sekcí...');
      const pagesData = [
        {
          slug: 'domu',
          title: 'Domů',
          content: JSON.stringify({
            heroTitle: 'Táta má právo. Dítě má právo na oba rodiče.',
            heroSubtitle: 'Komplexní opora pro otce v opatrovnických situacích.',
            published: true,
          }),
          sections: [
            {
              sectionKey: 'hero',
              title: 'Hlavní banner',
              content: 'Táta má právo. Dítě má právo na oba rodiče.',
              order: 1,
              config: JSON.stringify({ variant: 'primary' }),
            },
            {
              sectionKey: 'about_summary',
              title: 'O projektu',
              content: 'Všechna doporučení stavíme na nejlepším zájmu dítěte.',
              order: 2,
              config: JSON.stringify({ layout: 'centered' }),
            },
          ],
        },
        {
          slug: 'crisis',
          title: 'Krizová pomoc',
          content: JSON.stringify({
            heroTitle: '🚨 Krizový Akční Plán SOS',
            heroSubtitle: 'Okamžitá pomoc v akutních krizových situacích.',
            published: true,
          }),
          sections: [
            {
              sectionKey: 'sos_banner',
              title: 'Krizový SOS plán',
              content: 'První kroky při zamezení styku nebo krizové situaci s OSPOD.',
              order: 1,
              config: JSON.stringify({ alert: true }),
            },
          ],
        },
        {
          slug: 'opatrovnicka-agenda',
          title: 'Opatrovnictví',
          content: JSON.stringify({
            heroTitle: '⚖️ Opatrovnická agenda krok za krokem',
            heroSubtitle: 'Průvodce soudním řízením a jednáním s OSPOD.',
            published: true,
          }),
          sections: [
            {
              sectionKey: 'agenda_overview',
              title: 'Přehled řízení',
              content: 'Metodické postupy pro otce v opatrovnických sporech.',
              order: 1,
              config: JSON.stringify({ layout: 'grid' }),
            },
          ],
        },
        {
          slug: 'about',
          title: 'O nás',
          content: JSON.stringify({
            heroTitle: 'O projektu Táta má právo',
            heroSubtitle: 'Naše poslání, historie a tým.',
            published: true,
          }),
          sections: [
            {
              sectionKey: 'mission',
              title: 'Naše poslání',
              content: 'Obhajoba práva dítěte na rovnocennou péči obou rodičů.',
              order: 1,
              config: JSON.stringify({ variant: 'default' }),
            },
          ],
        },
        {
          slug: 'o-nas',
          title: 'O nás',
          content: JSON.stringify({
            heroTitle: 'O projektu Táta má právo',
            heroSubtitle: 'Obhajoba rovnocenné péče.',
            published: true,
          }),
          sections: [],
        },
      ];

      for (const p of pagesData) {
        const pageRecord = await prisma.page.upsert({
          where: { slug: p.slug },
          update: {
            title: p.title,
            content: p.content,
          },
          create: {
            title: p.title,
            slug: p.slug,
            content: p.content,
          },
        });

        await prisma.pageSection.deleteMany({ where: { pageId: pageRecord.id } });

        for (const sec of p.sections) {
          await prisma.pageSection.create({
            data: {
              pageId: pageRecord.id,
              sectionKey: sec.sectionKey,
              title: sec.title,
              content: sec.content,
              order: sec.order,
              config: sec.config,
            },
          });
        }
      }

      // 3. ZÁKLADNÍ KATEGORIE A FAQ
      console.log('[Prisma Seed] Seedování kategorií článků a FAQ...');
      const defaultCategories = [
        {
          slug: 'pravo',
          name: 'Právo',
          description: 'Právní výklady, rodinné právo, soudní judikatura a vyjádření.',
          type: 'article',
        },
        {
          slug: 'psychologie',
          name: 'Psychologie',
          description: 'Dětská psychologie, vazba k rodičům, prevence syndromu zavržení.',
          type: 'article',
        },
        {
          slug: 'metodika',
          name: 'Metodika',
          description: 'Metodické návody pro jednání s OSPOD, soudy a znalci.',
          type: 'article',
        },
      ];

      for (const cat of defaultCategories) {
        await prisma.category.upsert({
          where: { slug: cat.slug },
          update: {
            name: cat.name,
            description: cat.description,
            type: cat.type,
          },
          create: cat,
        });
      }

      const faqCategory = await prisma.category.findUnique({ where: { slug: 'pravo' } });
      const defaultFaqs = [
        {
          question: 'Co dělat, když mi matka bezdůvodně odpírá styk s dítětem?',
          answer: 'Okamžitě zdokumentujte každý neuskutečněný styk (SMS, e-mail, svědectví). Podejte návrh na vydání předběžného opatření a informujte OSPOD a příslušný okresní soud.',
          categoryName: 'Právo',
          categoryId: faqCategory?.id,
          order: 1,
          published: true,
        },
        {
          question: 'Jak se počítá výživné při střídavé péči?',
          answer: 'Při střídavé péči soud určuje výživné oběma rodičům podle jejich příjmů a rozsahu péče na základě doporučujících tabulek Ministerstva spravedlnosti ČR.',
          categoryName: 'Právo',
          categoryId: faqCategory?.id,
          order: 2,
          published: true,
        },
        {
          question: 'Má otec stejná práva na informace o zdravotním stavu a škole?',
          answer: 'Ano. Pokud nebyl otec zbaven rodičovské odpovědnosti nebo mu nebyla omezená, má plné právo nahlížet do zdravotní dokumentace dítěte a komunikovat se školou.',
          categoryName: 'Právo',
          categoryId: faqCategory?.id,
          order: 3,
          published: true,
        },
      ];

      await prisma.fAQ.deleteMany({});
      for (const f of defaultFaqs) {
        await prisma.fAQ.create({
          data: f,
        });
      }

      // 4. OPATROVNICKÉ SUBJEKTY ČR (Soudy, OSPOD, Krizová centra, Poradny)
      console.log('[Prisma Seed] Seedování opatrovnických subjektů ČR (14 krajů pomocí upsert)...');
      for (const s of realSubjektyData) {
        const savedSubjekt = await prisma.subjekt.upsert({
          where: { email: s.email },
          update: {
            type: s.type as any,
            name: s.name,
            position: s.position,
            institution: s.institution,
            city: s.city,
            region: s.region,
            address: s.address,
            phone: s.phone,
            website: s.website,
            isVerified: s.isVerified,
          },
          create: {
            type: s.type as any,
            name: s.name,
            position: s.position,
            institution: s.institution,
            city: s.city,
            region: s.region,
            address: s.address,
            email: s.email,
            phone: s.phone,
            website: s.website,
            isVerified: s.isVerified,
            avgRating: 0.0,
            reviewCount: 0,
          },
        });

        // Seed sample workers for OSPOD Přelouč
        if (s.email === 'podatelna@muprelouc.cz' || s.name.includes('Přelouč')) {
          const samplePracovnici = [
            {
              jmeno: 'Bc. Pavelková',
              pozice: 'Sociální pracovnice OSPOD',
              telefon: '+420 469 605 122',
              email: 'pavelkova@muprelouc.cz',
              kancelar: 'Kancelář č. 214',
            },
            {
              jmeno: 'Šejnová',
              pozice: 'Sociální pracovnice / Kurátorka',
              telefon: '+420 469 605 125',
              email: 'sejnova@muprelouc.cz',
              kancelar: 'Kancelář č. 216',
            },
          ];

          for (const p of samplePracovnici) {
            const existingPrac = await prisma.pracovnik.findFirst({
              where: {
                subjektId: savedSubjekt.id,
                jmeno: p.jmeno,
              },
            });
            if (!existingPrac) {
              await prisma.pracovnik.create({
                data: {
                  subjektId: savedSubjekt.id,
                  jmeno: p.jmeno,
                  pozice: p.pozice,
                  telefon: p.telefon,
                  email: p.email,
                  kancelar: p.kancelar,
                },
              });
            }
          }
        }
      }

      await runHelpNewsSeed();
      console.log('[Prisma Seed] Úspěšně naseedován výchozí CMS i Registr Subjektů v PostgreSQL!');
    } else {
      console.log('[Prisma Seed] Databáze není připojena, plním in-memory dbStore.');
    }

    // Synchronizace do in-memory dbStore
    seedInMemoryDbStore();
  } catch (err) {
    console.error('[Prisma Seed Error]:', err);
    seedInMemoryDbStore();
  }
}

function seedInMemoryDbStore() {
  dbStore.categories = [
    { id: 'cat-pravo', slug: 'pravo', name: 'Právo', description: 'Právní výklady, rodinné právo', type: 'article' },
    { id: 'cat-psychologie', slug: 'psychologie', name: 'Psychologie', description: 'Dětská psychologie', type: 'article' },
    { id: 'cat-metodika', slug: 'metodika', name: 'Metodika', description: 'Metodické návody pro OSPOD', type: 'article' },
  ];

  dbStore.faqs = [
    {
      id: 'faq-1',
      question: 'Co dělat, když mi matka bezdůvodně odpírá styk s dítětem?',
      answer: 'Okamžitě zdokumentujte každý neuskutečněný styk (SMS, e-mail, svědectví). Podejte návrh na vydání předběžného opatření a informujte OSPOD a příslušný okresní soud.',
      category: 'Právo',
      order: 1,
      published: true,
    },
    {
      id: 'faq-2',
      question: 'Jak se počítá výživné při střídavé péči?',
      answer: 'Při střídavé péči soud určuje výživné oběma rodičům podle jejich příjmů a rozsahu péče na základě doporučujících tabulek Ministerstva spravedlnosti ČR.',
      category: 'Právo',
      order: 2,
      published: true,
    },
    {
      id: 'faq-3',
      question: 'Má otec stejná práva na informace o zdravotním stavu a škole?',
      answer: 'Ano. Pokud nebyl otec zbaven rodičovské odpovědnosti nebo mu nebyla omezená, má plné právo nahlížet do zdravotní dokumentace dítěte a komunikovat se školou.',
      category: 'Právo',
      order: 3,
      published: true,
    },
  ];

  for (const s of realSubjektyData) {
    const exists = dbStore.subjekty.some((item) => item.name === s.name && item.city === s.city);
    if (!exists) {
      dbStore.subjekty.push({
        id: 'subj-' + Math.random().toString(36).substring(2, 9),
        type: s.type as any,
        name: s.name,
        position: s.position,
        institution: s.institution,
        city: s.city,
        region: s.region,
        address: s.address,
        email: s.email,
        phone: s.phone,
        website: s.website,
        avgRating: 0.0,
        reviewCount: 0,
        isVerified: s.isVerified,
        createdAt: new Date(),
        reviews: [],
      });
    }
  }
}

// Podpora přímého spuštění přes CLI (`npx prisma db seed` / `tsx prisma/seed.ts`)
if (import.meta.url === `file://${process.argv[1]}` || process.argv[1]?.endsWith('seed.ts')) {
  runSeed()
    .then(() => {
      console.log('[Prisma Seed CLI] Dokončeno.');
      process.exit(0);
    })
    .catch((err) => {
      console.error('[Prisma Seed CLI Error]:', err);
      process.exit(1);
    });
}

